# Pinhole Camera Model Practice Questions

## Question 1: Perspective Projection

A 3D point in the camera coordinate system is given by `p_c = [10, 5, 20]`. 
The camera has a focal length `f` of 50mm. 
Calculate the position of the projection of this point on the image plane in meters.

In [5]:


p_c = [10, 5, 20]
f_mm = 50
f_m = f_mm/1000

x = f_m * p_c[0] / p_c[2]
y = f_m * p_c[1] / p_c[2]

p_cz = [x, y]
print (p_cz)

[0.025, 0.0125]


---

## Question 2: Conversion to Pixels

Given the projected point from Question 1, convert its coordinates from meters to pixels. 
Assume the following intrinsic parameters: 
- `s_x` = 800 pixels/meter
- `s_y` = 800 pixels/meter
- `o_x` = 320 pixels
- `o_y` = 240 pixels
What are the pixel coordinates `(u^I, v^I)`?

In [7]:
s_x = 800
s_y = 800
o_x = 320
o_y = 240

p_cz_p = [s_x * x + o_x, s_y * y + o_y]

print(p_cz_p)

[340.0, 250.0]


---

## Question 3: Intrinsic Matrix

Construct the intrinsic calibration matrix `K` using the parameters from Question 2, assuming no skew (`s_θ = 0`).

In [11]:
k = [[s_x, 0, o_x],
     [0, s_y, o_y],
     [0, 0, 1]]
for i in k:
    print(i)

[800, 0, 320]
[0, 800, 240]
[0, 0, 1]


---

## Question 4: Point Projection with Known Pose

A point in the world frame is given by `p_w = [2, 3, 50]`. The camera's pose `T_w^c` is given by an identity rotation matrix and a translation vector `t_w^c = [0, 0, 10]`. [cite_start]Using the intrinsic matrix `K` from Question 3, calculate the pixel coordinates of the projected point. [cite: 14, 16, 17]

In [13]:
p_w = [2, 3, 60]

x_w = p_w[0] / p_w[2]
y_w = p_w[1] / p_w[2]

p_w_p = [s_x * x_w + o_x, s_y * y_w + o_y]

print (p_w_p)

[346.6666666666667, 280.0]


---

## Question 5: Radial Distortion

A point is projected on the image plane at `(u_distort^I, v_distort^I) = (400, 350)` including radial distortion. Given distortion coefficients `a1 = 0.0001` and `a2 = 0.0000002` and the principal point `(o_x, o_y) = (320, 240)`, calculate the corrected pixel coordinates `(u^I, v^I)`.

In [14]:
u_distort_I = 400
v_distort_I = 350
a1 = 0.0001
a2 = 0.0000002

r_2 = (u_distort_I - o_x)**2 + (v_distort_I - o_y)**2
u_I = (1 + a1 * r_2 + a2 * r_2**2) * (u_distort_I - o_x) + o_x
v_I = (1 + a1 * r_2 + a2 * r_2**2) * (v_distort_I - o_y) + o_y

print(u_I)
print(v_I)

6024.0
8083.0
